package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var initForce bool

var initCmd = &cobra.Command{
	Use:   "init [path]",
	Short: "Generate a .secretsvet.yaml config file",
	Long: `Generate a .secretsvet.yaml configuration file tailored to the current repository.

secretsvet init scans the repository structure and suggests sensible defaults:
  - Detects Helm charts and adds chart-specific ignore patterns
  - Detects Kustomize overlays and suggests secretGenerator guidance
  - Detects test directories and offers to exclude them
  - Creates a starter .secretsvet.yaml with commented-out options

Examples:
  secretsvet init           # generate .secretsvet.yaml in the current directory
  secretsvet init /repo     # generate for a specific path
  secretsvet init --force   # overwrite existing .secretsvet.yaml`,
	Args: cobra.MaximumNArgs(1),
	RunE: runInit,
}

func init() {
	initCmd.Flags().BoolVar(&initForce, "force", false, "Overwrite existing .secretsvet.yaml")
	rootCmd.AddCommand(initCmd)
}

func runInit(_ *cobra.Command, args []string) error {
	root := "."
	if len(args) > 0 {
		root = args[0]
	}

	outPath := filepath.Join(root, ".secretsvet.yaml")

	// Check if file already exists
	if _, err := os.Stat(outPath); err == nil && !initForce {
		return fmt.Errorf("%s already exists (use --force to overwrite)", outPath)
	}

	// Detect repo characteristics
	detection := detectRepo(root)

	// Build config content
	content := buildInitConfig(detection)

	if err := os.WriteFile(outPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	// Print summary
	fmt.Printf("Created %s\n\n", outPath)
	fmt.Println("Detected:")
	for _, line := range detection.summary {
		fmt.Printf("  %s\n", line)
	}
	fmt.Printf("\nNext steps:\n")
	fmt.Printf("  1. Review %s and uncomment rules you want to customize\n", outPath)
	fmt.Printf("  2. Run 'secretsvet scan .' to see current findings\n")
	fmt.Printf("  3. Save a baseline: secretsvet scan . --output json | jq '.findings' > .secretsvet-baseline.json\n")
	fmt.Printf("     Then scan with: secretsvet scan . --baseline .secretsvet-baseline.json\n")
	return nil
}

type repoDetection struct {
	hasHelm        bool
	hasKustomize   bool
	hasTestDirs    bool
	hasEnvFiles    bool
	hasGitHistory  bool
	testDirs       []string
	helmCharts     []string
	summary        []string
}

func detectRepo(root string) repoDetection {
	d := repoDetection{}

	_ = filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		// Skip hidden dirs (except root)
		if entry.IsDir() && strings.HasPrefix(entry.Name(), ".") && path != root {
			return filepath.SkipDir
		}
		// Skip vendor, node_modules
		if entry.IsDir() && (entry.Name() == "vendor" || entry.Name() == "node_modules") {
			return filepath.SkipDir
		}

		name := entry.Name()

		if !entry.IsDir() {
			switch name {
			case "Chart.yaml":
				d.hasHelm = true
				d.helmCharts = append(d.helmCharts, filepath.Dir(path))
			case "kustomization.yaml", "kustomization.yml":
				d.hasKustomize = true
			case ".git":
				d.hasGitHistory = true
			}
			// .env files
			lower := strings.ToLower(name)
			if lower == ".env" || strings.HasPrefix(lower, ".env.") {
				d.hasEnvFiles = true
			}
		} else {
			// Test directories
			lower := strings.ToLower(name)
			if lower == "test" || lower == "tests" || lower == "testdata" || lower == "fixtures" {
				d.hasTestDirs = true
				rel, _ := filepath.Rel(root, path)
				d.testDirs = append(d.testDirs, rel)
			}
		}
		return nil
	})

	// Also check for .git directory
	if _, err := os.Stat(filepath.Join(root, ".git")); err == nil {
		d.hasGitHistory = true
	}

	// Build summary
	if d.hasHelm {
		if len(d.helmCharts) == 1 {
			d.summary = append(d.summary, fmt.Sprintf("✓ Helm chart found at %s", d.helmCharts[0]))
		} else {
			d.summary = append(d.summary, fmt.Sprintf("✓ %d Helm charts found", len(d.helmCharts)))
		}
	}
	if d.hasKustomize {
		d.summary = append(d.summary, "✓ Kustomize configuration found")
	}
	if d.hasGitHistory {
		d.summary = append(d.summary, "✓ Git repository (git-scan available)")
	}
	if d.hasTestDirs {
		d.summary = append(d.summary, fmt.Sprintf("✓ Test directories: %s", strings.Join(d.testDirs, ", ")))
	}
	if d.hasEnvFiles {
		d.summary = append(d.summary, "! .env file(s) found — run 'secretsvet git-scan .' to check history")
	}
	if len(d.summary) == 0 {
		d.summary = append(d.summary, "(nothing specific detected — using defaults)")
	}

	return d
}

func buildInitConfig(d repoDetection) string {
	var b strings.Builder

	b.WriteString("# .secretsvet.yaml — SecretsVet project configuration\n")
	b.WriteString("# Generated by 'secretsvet init'\n")
	b.WriteString("# Run 'secretsvet rules' to see all available rule IDs.\n")
	b.WriteString("\n")

	// Rules section
	b.WriteString("# Per-rule overrides\n")
	b.WriteString("# rules:\n")
	b.WriteString("#   SV1070:\n")
	b.WriteString("#     disabled: false        # enable/disable a rule\n")
	b.WriteString("#     severity: HIGH          # override severity: CRITICAL, HIGH, MEDIUM, LOW\n")

	if d.hasHelm {
		b.WriteString("#   SV6040:\n")
		b.WriteString("#     disabled: true         # uncomment if you intentionally use Helm-managed Secrets\n")
	}
	b.WriteString("\n")

	// Thresholds section
	b.WriteString("# Detection sensitivity\n")
	b.WriteString("# thresholds:\n")
	b.WriteString("#   entropy_min_length: 20    # minimum length for entropy-based detection (default: 20)\n")
	b.WriteString("#                              # increase to reduce false positives, decrease to catch shorter secrets\n")
	b.WriteString("\n")

	// Ignore section
	b.WriteString("# Paths to exclude from scanning (glob patterns)\n")
	b.WriteString("# ignore:\n")
	b.WriteString("#   paths:\n")

	if d.hasTestDirs {
		for _, dir := range d.testDirs {
			b.WriteString(fmt.Sprintf("#     - %s/**\n", dir))
		}
		b.WriteString("#     - \"**/*_test.yaml\"\n")
	} else {
		b.WriteString("#     - tests/**\n")
		b.WriteString("#     - \"**/*_test.yaml\"\n")
	}

	if d.hasHelm {
		b.WriteString("#     - \"**/charts/**\"       # exclude vendored Helm dependencies\n")
	}

	b.WriteString("#     - docs/**               # exclude documentation examples\n")
	b.WriteString("\n")

	return b.String()
}
